ALTER TABLE orders ADD COLUMN IF NOT EXISTS checkout_url TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS checkout_key VARCHAR(255) UNIQUE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_started BOOLEAN NOT NULL DEFAULT FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS orders_one_per_call ON orders(call_id) WHERE call_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS guest_sessions (
 token VARCHAR(64) PRIMARY KEY, cart JSONB NOT NULL DEFAULT '[]',
 call_id VARCHAR(255) UNIQUE, voice_token VARCHAR(64), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
